/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EuropeBusBookingV2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.*;
import java.awt.*;
import java.util.Arrays;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ishan
 */
public class UserMenu extends javax.swing.JFrame {
    
    
    Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement pst2 = null;
    PreparedStatement pst3 = null;

    /**
     * Creates new form UserMenu
     */
    public UserMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DestinationFilter = new javax.swing.JTextField();
        DepartureFilter = new javax.swing.JTextField();
        ShowTrips = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BookUsername = new javax.swing.JTextField();
        BookBusNo = new javax.swing.JTextField();
        BookDeparture = new javax.swing.JTextField();
        BookDestination = new javax.swing.JTextField();
        BookDay = new javax.swing.JTextField();
        BookTime = new javax.swing.JTextField();
        BookPrice = new javax.swing.JTextField();
        BookButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(43, 6, 78));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gilroy ExtraBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(223, 240, 247));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BOOK YOUR COACH TICKET");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 480, 60));

        jLabel3.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(223, 240, 247));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Destination");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 90, 30));

        jLabel2.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(223, 240, 247));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Departure");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 90, 30));
        jPanel1.add(DestinationFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 170, 30));
        jPanel1.add(DepartureFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 170, 30));

        ShowTrips.setText("SHOW");
        ShowTrips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTripsActionPerformed(evt);
            }
        });
        jPanel1.add(ShowTrips, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 90, 30));

        jTable1.setBackground(new java.awt.Color(223, 240, 247));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BusNo", "DepCountry", "DepCity", "DesCountry", "DesCity", "Day", "Time", "Price", "Capacity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 660, 350));

        jPanel2.setBackground(new java.awt.Color(223, 240, 247));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        jLabel4.setText("Bus Number");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 101, 107, 24));

        jLabel5.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        jLabel5.setText("Username");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 59, 107, 24));

        jLabel6.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        jLabel6.setText("Destination");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 185, 107, 24));

        jLabel7.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        jLabel7.setText("Departure");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 143, 107, 24));

        jLabel8.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        jLabel8.setText("Day");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 227, 107, 24));

        jLabel9.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        jLabel9.setText("Time");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 269, 107, 24));

        jLabel10.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        jLabel10.setText("Price");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 311, 107, 24));

        BookUsername.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        BookUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(BookUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 60, 163, -1));

        BookBusNo.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        BookBusNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(BookBusNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 102, 163, -1));

        BookDeparture.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        BookDeparture.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(BookDeparture, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 144, 163, -1));

        BookDestination.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        BookDestination.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BookDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookDestinationActionPerformed(evt);
            }
        });
        jPanel2.add(BookDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 186, 163, -1));

        BookDay.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        BookDay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(BookDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 228, 163, -1));

        BookTime.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        BookTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BookTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookTimeActionPerformed(evt);
            }
        });
        jPanel2.add(BookTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 270, 163, -1));

        BookPrice.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        BookPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(BookPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 312, 163, -1));

        BookButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BookButton.setText("BOOK");
        BookButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookButtonActionPerformed(evt);
            }
        });
        jPanel2.add(BookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 130, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 360, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BookDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookDestinationActionPerformed

    private void BookTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookTimeActionPerformed

    private void ShowTripsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTripsActionPerformed
        // TODO add your handling code here:
        String departure = DepartureFilter.getText();
        String destination = DestinationFilter.getText();
        
        try{
            String query = "select * from busregister where DepartureCity=? and DestinationCity=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/eurobusbooking", "root", "");
            pst =  con.prepareStatement(query);
            pst.setString(1, departure);
            pst.setString(2, destination);
            
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rsd = rs.getMetaData();
            int c;
            
            c = rsd.getColumnCount();
            
            DefaultTableModel d = (DefaultTableModel)jTable1.getModel();
            d.setRowCount(0);
            
            while(rs.next()){
                
                Vector v2 = new Vector();
                
                for (int i = 1; i<=c;i++){
                    //System.out.println("Here");
                    
                    v2.add(rs.getString("BusNo"));
                    v2.add(rs.getString("DepartureCountry"));
                    v2.add(rs.getString("DepartureCity"));
                    v2.add(rs.getString("DestinationCountry"));
                    v2.add(rs.getString("DestinationCity"));
                    v2.add(rs.getString("Day"));
                    v2.add(rs.getString("Time"));
                    v2.add(rs.getString("Price"));
                    v2.add(rs.getString("Capacity"));
                    
                    
                }
                d.addRow(v2);
            }
            
            
            
            
            
        
        
        }catch(Exception ex ){
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(AdminMenu.class.getName()).log(Level.SEVERE, null, ex);
        
        
        }
        
        
        
    }//GEN-LAST:event_ShowTripsActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selected = jTable1.getSelectedRow();
        
        
        String busnumber = d1.getValueAt(selected, 0).toString();
        String depcity = d1.getValueAt(selected, 2).toString();
        String descity = d1.getValueAt(selected, 4).toString();
        String day = d1.getValueAt(selected, 5).toString();
        String time = d1.getValueAt(selected, 6).toString();
        String price = d1.getValueAt(selected, 7).toString();
        
        BookBusNo.setText(busnumber);
        BookDeparture.setText(depcity);
        BookDestination.setText(descity);
        BookDay.setText(day);
        BookTime.setText(time);
        BookPrice.setText(price);
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void BookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookButtonActionPerformed
        // TODO add your handling code here:
        
        try{
            String query = "INSERT INTO `bookregister`(`Username`, `BusNo`, `Departure`, `Destination`, `Day`, `Time`, `Price`) VALUES (?,?,?,?,?,?,?)";
            
            
            con = DriverManager.getConnection("jdbc:mysql://localhost/eurobusbooking", "root", "");
            pst =  con.prepareStatement(query);
            
            pst.setString(1, BookUsername.getText());
            pst.setString(2, BookBusNo.getText());
            pst.setString(3, BookDeparture.getText());
            pst.setString(4, BookDestination.getText());
            pst.setString(5, BookDay.getText());
            pst.setString(6, BookTime.getText());
            pst.setString(7, BookPrice.getText());
            
            
            
            pst.executeUpdate();
           
            JOptionPane.showMessageDialog(null, "BOOKED!!!");
            
        
        
        }catch(Exception ex ){
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(AdminMenu.class.getName()).log(Level.SEVERE, null, ex);
        
        
        }
        
    }//GEN-LAST:event_BookButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BookBusNo;
    private javax.swing.JButton BookButton;
    private javax.swing.JTextField BookDay;
    private javax.swing.JTextField BookDeparture;
    private javax.swing.JTextField BookDestination;
    private javax.swing.JTextField BookPrice;
    private javax.swing.JTextField BookTime;
    private javax.swing.JTextField BookUsername;
    private javax.swing.JTextField DepartureFilter;
    private javax.swing.JTextField DestinationFilter;
    private javax.swing.JButton ShowTrips;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
